### ISSUE TITLE
un-necessary padspaces added to (others => '0')

### ISSUE THREAD

**Issue by gutelfuldead** [g2384/VHDLFormatter#14]
## Report a bug
When a stdlv/unsigned is having its assignment aligned, the numbers of spaces between the name and assignment is also copied between the "others" and "=" in (others => '0'). 

Selected options,
Align signs in PORT, GENERIC, PROCEDURE, FUNCTION
align signs in all places
customize indentation (four blankspaces)

Thanks

### Input
```
		unsigned_idle_packets <= (others => '0');
		unsigned_crc_error_count_packets <= (others => '0');
		unsigned_tlast_error_count_packets <= (others => '0');
		unsigned_unknown_vcid_count_packets <= (others => '0');
```

### Expected Behavior
```
unsigned_idle_packets               <= (OTHERS => '0');
unsigned_crc_error_count_packets    <= (OTHERS => '0');
unsigned_tlast_error_count_packets  <= (OTHERS => '0');
unsigned_unknown_vcid_count_packets <= (OTHERS => '0');
```

### Actual Behavior
```
unsigned_idle_packets               <= (OTHERS               => '0');
unsigned_crc_error_count_packets    <= (OTHERS    => '0');
unsigned_tlast_error_count_packets  <= (OTHERS  => '0');
unsigned_unknown_vcid_count_packets <= (OTHERS => '0');
```

**Comment by g2384** [comment]
Thanks again, it's fixed now.
Your browser should remember your settings now.
Feel free to refresh that page at any time.
