### ISSUE TITLE
Request to align signal types after IO

### ISSUE THREAD

**Issue by are512** [g2384/VHDLFormatter#24]
### As a user, I want to...
Be able to align the signal types after IO's

#### Example Input:
```
SIGNAL sig_1 : IN std_ulogic;
SIGNAL sig_2 : OUT std_ulogic;
SIGNAL sig_3 : INOUT std_ulogic;
```

#### Example Output:
```
SIGNAL sig_1 : IN    std_ulogic;
SIGNAL sig_2 : OUT   std_ulogic;
SIGNAL sig_3 : INOUT std_ulogic;
```

**Comment by g2384** [comment]
Good one! I don't have enery to implement this yet. :(

**Comment by g2384** [comment]
Thanks for your contribution. I've extended it to cover in, out, buffer, and inout.  This issue is fixed now.
