### ISSUE TITLE
single line package declarations indent

### ISSUE THREAD

**Issue by are512** [g2384/VHDLFormatter#25]
### Input
```PACKAGE p IS NEW work.p_template;```

### Expected Behavior
Should not indent after declaration

### Actual Behavior
Does indent after declaration, hence the rest of the file become out of sync by one indent level

**Comment by are512** [comment]
Ignore second commit, that was part of a deleted branch, so just first and third

**Comment by g2384** [comment]
this bug is fixed now. Sorry that your PR doesn't cover all cases.
