### ISSUE TITLE
Keywords used in reports/strings are affected by the casing option

### ISSUE THREAD

**Issue by goglecm** [g2384/VHDLFormatter#3]
When keywords are used in reports or strings they become uppercase/lowercase depending on how you set the Keyword Case option.
This should not happen. When a file name is specified and it gets changed, the file can no longer be found.
An example of where this occurred:
REPORT
            "A_ARITH_MOD_tester.main Tester IS now ready. A total OF " &
            INTEGER'image(totalTests) & " tests have been detected.";

**Comment by g2384** [comment]
Fixed
